import { useState, useEffect } from 'react'
import { useParams } from 'react-router-dom'
import { timetableApi, scheduleApi } from '../api/api'
import './TimetablePage.css'

const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
const HOURS = Array.from({ length: 16 }, (_, i) => i + 6)

export default function SharedTimetablePage() {
    const { token } = useParams()
    const [active, setActive] = useState(null)
    const [entries, setEntries] = useState([])
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState(null)

    useEffect(() => {
        const load = async () => {
            try {
                const r = await timetableApi.getShared(token)
                setActive(r.data)
                // Schedule entries for public view
                // Since we don't have a public endpoint for entries yet, 
                // we should expose them in the Timetable entity or add a public endpoint.
                // For now, let's assume the backend provides them in the Timetable response 
                // or we use the existing endpoint (if allowed).
                // I'll update the backend to include entries in the getShared response.
                setEntries(r.data.entries || [])
            } catch (err) {
                setError('Schedule not found or private.')
            } finally {
                setLoading(false)
            }
        }
        load()
    }, [token])

    const entryStyle = (e) => {
        const [sh, sm] = e.startTime.split(':').map(Number)
        const [eh, em] = e.endTime.split(':').map(Number)
        const top = (sh - 6) * 60 + sm
        const height = (eh - 6) * 60 + em - top
        return { top: `${top}px`, height: `${Math.max(height, 30)}px`, background: '#6366f1' }
    }

    if (loading) return <div className="page fade-in"><div className="spinner" /> Loading public schedule...</div>
    if (error) return <div className="page fade-in"><div className="glass-card empty-state"><h3>404</h3><p>{error}</p></div></div>

    return (
        <div className="page fade-in">
            <div className="page-header">
                <div>
                    <h1>{active.name}</h1>
                    <p>Public Read-only Schedule</p>
                </div>
            </div>

            <div className="weekly-grid-wrap glass-card" style={{ padding: 0, overflow: 'hidden' }}>
                <div className="weekly-grid">
                    <div className="grid-time-col" />
                    {DAYS.map(d => <div key={d} className="grid-day-header">{d}</div>)}

                    {HOURS.map(h => (
                        <div key={h} style={{ display: 'contents' }}>
                            <div className="grid-time-label">{h}:00</div>
                            {DAYS.map((_, di) => (
                                <div key={`cell${h}${di}`} className="grid-cell" style={{ position: 'relative' }}>
                                    {h === 6 && entries.filter(e => e.dayOfWeek === di).map(e => (
                                        <div key={e.id} className="grid-entry" style={entryStyle(e)}>
                                            <span className="entry-title">{e.title}</span>
                                            <span className="entry-time">{e.startTime}–{e.endTime}</span>
                                        </div>
                                    ))}
                                </div>
                            ))}
                        </div>
                    ))}
                </div>
            </div>
            
            <div style={{ marginTop: 40, textAlign: 'center', opacity: 0.6 }}>
                <p>Generated by FocusFlow</p>
            </div>
        </div>
    )
}
