package com.timetable.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.timetable.model.dto.TaskResponse;
import com.timetable.model.entity.User;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
@Slf4j
public class PdfReportService {

    // ── Brand Colors ────────────────────────────────────────────
    private static final Color BRAND_DARK   = new Color(10, 10, 15);
    private static final Color BRAND_VIOLET = new Color(139, 92, 246);
    private static final Color BRAND_CYAN   = new Color(6, 182, 212);
    private static final Color ACCENT_GREEN = new Color(16, 185, 129);
    private static final Color ACCENT_RED   = new Color(239, 68, 68);
    private static final Color ACCENT_AMBER = new Color(245, 158, 11);
    private static final Color TEXT_PRIMARY  = new Color(255, 255, 255);
    private static final Color TEXT_SECONDARY= new Color(163, 163, 163);
    private static final Color TEXT_MUTED    = new Color(82, 82, 82);
    private static final Color CARD_BG      = new Color(18, 18, 22);
    private static final Color CARD_BORDER  = new Color(40, 40, 50);
    private static final Color TABLE_ROW_ALT= new Color(15, 15, 20);
    private static final Color TABLE_HEADER = new Color(99, 102, 241);

    // ── Fonts ───────────────────────────────────────────────────
    private Font fontBrand()    { return FontFactory.getFont(FontFactory.HELVETICA_BOLD, 28, TEXT_PRIMARY); }
    private Font fontTitle()    { return FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, TEXT_PRIMARY); }
    private Font fontSubtitle() { return FontFactory.getFont(FontFactory.HELVETICA, 11, TEXT_SECONDARY); }
    private Font fontSection()  { return FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, BRAND_VIOLET); }
    private Font fontBody()     { return FontFactory.getFont(FontFactory.HELVETICA, 10, TEXT_PRIMARY); }
    private Font fontSmall()    { return FontFactory.getFont(FontFactory.HELVETICA, 8.5f, TEXT_MUTED); }
    private Font fontMetric()   { return FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, TEXT_PRIMARY); }
    private Font fontMetricLabel() { return FontFactory.getFont(FontFactory.HELVETICA, 8, TEXT_SECONDARY); }
    private Font fontTableHead(){ return FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, TEXT_PRIMARY); }
    private Font fontTableBody(){ return FontFactory.getFont(FontFactory.HELVETICA, 9, new Color(220, 220, 220)); }

    public byte[] generateTasksReport(User user, List<TaskResponse> tasks) {
        Document document = new Document(PageSize.A4, 36, 36, 40, 40);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter writer = PdfWriter.getInstance(document, out);
            writer.setPageEvent(new DarkPageEvent());
            document.open();

            // ── HERO HEADER ─────────────────────────────────────
            addHeroHeader(document, user);

            // ── KPI DASHBOARD CARDS ─────────────────────────────
            addKpiCards(document, tasks);

            // ── PRIORITY BREAKDOWN ──────────────────────────────
            addPriorityBreakdown(document, tasks);

            // ── CATEGORY BREAKDOWN ──────────────────────────────
            addCategoryBreakdown(document, tasks);

            // ── TASK TABLE ──────────────────────────────────────
            addTaskTable(document, tasks);

            // ── FOOTER NOTE ─────────────────────────────────────
            document.add(spacer(24));
            addSeparator(document);
            Paragraph footer = new Paragraph(
                "Generated by FocusFlow · " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMMM d, yyyy 'at' HH:mm")),
                fontSmall()
            );
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(12);
            document.add(footer);

            document.close();

        } catch (DocumentException e) {
            log.error("Error creating PDF document", e);
        }

        return out.toByteArray();
    }

    // ── HERO HEADER ─────────────────────────────────────────────
    private void addHeroHeader(Document doc, User user) throws DocumentException {
        PdfPTable header = new PdfPTable(2);
        header.setWidthPercentage(100);
        header.setWidths(new float[]{3f, 2f});

        // Left: Brand + Title
        PdfPCell left = new PdfPCell();
        left.setBorder(Rectangle.NO_BORDER);
        left.setPadding(0);
        left.setBackgroundColor(BRAND_DARK);

        Paragraph brand = new Paragraph("FocusFlow", fontBrand());
        brand.setSpacingAfter(4);
        left.addElement(brand);

        Paragraph subtitle = new Paragraph("PRODUCTIVITY REPORT", FontFactory.getFont(FontFactory.HELVETICA, 10, BRAND_VIOLET));
        subtitle.setSpacingAfter(12);
        left.addElement(subtitle);

        Paragraph userName = new Paragraph(user.getName(), FontFactory.getFont(FontFactory.HELVETICA, 11, TEXT_PRIMARY));
        left.addElement(userName);

        Paragraph email = new Paragraph(user.getEmail(), fontSmall());
        left.addElement(email);

        header.addCell(left);

        // Right: Date block
        PdfPCell right = new PdfPCell();
        right.setBorder(Rectangle.NO_BORDER);
        right.setBackgroundColor(BRAND_DARK);
        right.setHorizontalAlignment(Element.ALIGN_RIGHT);
        right.setVerticalAlignment(Element.ALIGN_BOTTOM);
        right.setPadding(0);

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMM dd, yyyy");
        DateTimeFormatter timeFmt = DateTimeFormatter.ofPattern("HH:mm");
        LocalDateTime now = LocalDateTime.now();

        Paragraph dateLabel = new Paragraph("REPORT DATE", fontSmall());
        dateLabel.setAlignment(Element.ALIGN_RIGHT);
        right.addElement(dateLabel);

        Paragraph dateVal = new Paragraph(now.format(dtf), FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, TEXT_PRIMARY));
        dateVal.setAlignment(Element.ALIGN_RIGHT);
        right.addElement(dateVal);

        Paragraph timeVal = new Paragraph(now.format(timeFmt), fontSmall());
        timeVal.setAlignment(Element.ALIGN_RIGHT);
        right.addElement(timeVal);

        header.addCell(right);

        doc.add(header);
        doc.add(spacer(8));
        addGradientBar(doc);
        doc.add(spacer(20));
    }

    // ── KPI CARDS ───────────────────────────────────────────────
    private void addKpiCards(Document doc, List<TaskResponse> tasks) throws DocumentException {
        long total = tasks.size();
        long completed = tasks.stream().filter(t -> "COMPLETED".equals(t.getStatus().name())).count();
        long inProgress = tasks.stream().filter(t -> "IN_PROGRESS".equals(t.getStatus().name())).count();
        long pending = total - completed - inProgress;
        double completionRate = total > 0 ? (completed * 100.0 / total) : 0;

        PdfPTable kpi = new PdfPTable(4);
        kpi.setWidthPercentage(100);
        kpi.setSpacingAfter(20);

        addKpiCell(kpi, String.valueOf(total), "TOTAL TASKS", BRAND_VIOLET);
        addKpiCell(kpi, String.valueOf(completed), "COMPLETED", ACCENT_GREEN);
        addKpiCell(kpi, String.valueOf(inProgress), "IN PROGRESS", BRAND_CYAN);
        addKpiCell(kpi, String.format("%.0f%%", completionRate), "COMPLETION", completionRate >= 70 ? ACCENT_GREEN : ACCENT_AMBER);

        doc.add(kpi);
    }

    private void addKpiCell(PdfPTable table, String value, String label, Color accent) {
        PdfPCell cell = new PdfPCell();
        cell.setBackgroundColor(CARD_BG);
        cell.setBorderColor(CARD_BORDER);
        cell.setBorderWidth(1);
        cell.setPadding(14);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);

        Paragraph val = new Paragraph(value, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24, accent));
        val.setAlignment(Element.ALIGN_CENTER);
        cell.addElement(val);

        Paragraph lbl = new Paragraph(label, FontFactory.getFont(FontFactory.HELVETICA, 7, TEXT_MUTED));
        lbl.setAlignment(Element.ALIGN_CENTER);
        lbl.setSpacingBefore(4);
        cell.addElement(lbl);

        table.addCell(cell);
    }

    // ── PRIORITY BREAKDOWN ──────────────────────────────────────
    private void addPriorityBreakdown(Document doc, List<TaskResponse> tasks) throws DocumentException {
        Paragraph section = new Paragraph("Priority Distribution", fontSection());
        section.setSpacingAfter(10);
        doc.add(section);

        Map<String, Long> counts = tasks.stream()
            .collect(Collectors.groupingBy(
                t -> t.getPriority() != null ? t.getPriority().name() : "MEDIUM",
                Collectors.counting()
            ));

        PdfPTable grid = new PdfPTable(4);
        grid.setWidthPercentage(100);
        grid.setSpacingAfter(20);

        String[] priorities = {"URGENT", "HIGH", "MEDIUM", "LOW"};
        Color[] colors = {ACCENT_RED, new Color(249, 115, 22), ACCENT_AMBER, ACCENT_GREEN};

        for (int i = 0; i < priorities.length; i++) {
            long count = counts.getOrDefault(priorities[i], 0L);
            PdfPCell cell = new PdfPCell();
            cell.setBackgroundColor(CARD_BG);
            cell.setBorderColor(CARD_BORDER);
            cell.setBorderWidth(1);
            cell.setPadding(10);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);

            // Priority dot + label
            Paragraph dot = new Paragraph("●", FontFactory.getFont(FontFactory.HELVETICA, 12, colors[i]));
            dot.setAlignment(Element.ALIGN_CENTER);
            cell.addElement(dot);

            Paragraph num = new Paragraph(String.valueOf(count), FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, TEXT_PRIMARY));
            num.setAlignment(Element.ALIGN_CENTER);
            cell.addElement(num);

            Paragraph lbl = new Paragraph(priorities[i], FontFactory.getFont(FontFactory.HELVETICA, 7, TEXT_MUTED));
            lbl.setAlignment(Element.ALIGN_CENTER);
            cell.addElement(lbl);

            grid.addCell(cell);
        }

        doc.add(grid);
    }

    // ── CATEGORY BREAKDOWN ──────────────────────────────────────
    private void addCategoryBreakdown(Document doc, List<TaskResponse> tasks) throws DocumentException {
        Map<String, Long> catCounts = tasks.stream()
            .collect(Collectors.groupingBy(
                t -> t.getCategoryName() != null ? t.getCategoryName() : "Uncategorized",
                Collectors.counting()
            ));

        if (catCounts.isEmpty()) return;

        Paragraph section = new Paragraph("Tasks by Category", fontSection());
        section.setSpacingAfter(10);
        doc.add(section);

        PdfPTable catTable = new PdfPTable(3);
        catTable.setWidthPercentage(100);
        catTable.setWidths(new float[]{4f, 1.5f, 2f});
        catTable.setSpacingAfter(20);

        // Header
        String[] catHeaders = {"CATEGORY", "COUNT", "SHARE"};
        for (String h : catHeaders) {
            PdfPCell hc = new PdfPCell(new Phrase(h, fontTableHead()));
            hc.setBackgroundColor(new Color(25, 25, 35));
            hc.setBorderColor(CARD_BORDER);
            hc.setPadding(8);
            catTable.addCell(hc);
        }

        long totalTasks = tasks.size();
        boolean alt = false;
        for (Map.Entry<String, Long> entry : catCounts.entrySet()) {
            Color rowBg = alt ? TABLE_ROW_ALT : CARD_BG;
            double share = totalTasks > 0 ? (entry.getValue() * 100.0 / totalTasks) : 0;

            addTableCell(catTable, entry.getKey(), fontTableBody(), rowBg);
            addTableCell(catTable, String.valueOf(entry.getValue()), fontTableBody(), rowBg);
            addTableCell(catTable, String.format("%.1f%%", share), fontTableBody(), rowBg);
            alt = !alt;
        }

        doc.add(catTable);
    }

    // ── TASK TABLE ──────────────────────────────────────────────
    private void addTaskTable(Document doc, List<TaskResponse> tasks) throws DocumentException {
        Paragraph section = new Paragraph("All Tasks", fontSection());
        section.setSpacingAfter(10);
        doc.add(section);

        PdfPTable table = new PdfPTable(5);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{3.5f, 1.8f, 1.5f, 1.5f, 2f});

        // Header row
        String[] headers = {"TASK", "CATEGORY", "PRIORITY", "STATUS", "DEADLINE"};
        for (String headerTitle : headers) {
            PdfPCell header = new PdfPCell(new Phrase(headerTitle, fontTableHead()));
            header.setBackgroundColor(TABLE_HEADER);
            header.setBorderColor(new Color(79, 82, 221));
            header.setPadding(10);
            header.setBorderWidth(0.5f);
            table.addCell(header);
        }

        // Body rows
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMM dd, yyyy");
        boolean alt = false;
        for (TaskResponse task : tasks) {
            Color rowBg = alt ? TABLE_ROW_ALT : CARD_BG;

            addTableCell(table, task.getTitle() != null ? task.getTitle() : "N/A", fontTableBody(), rowBg);
            addTableCell(table, task.getCategoryName() != null ? task.getCategoryName() : "—", fontTableBody(), rowBg);

            // Priority with color
            String priority = task.getPriority() != null ? task.getPriority().name() : "MEDIUM";
            Color priorityColor = getPriorityColor(priority);
            PdfPCell prioCell = new PdfPCell(new Phrase(priority, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, priorityColor)));
            prioCell.setBackgroundColor(rowBg);
            prioCell.setBorderColor(CARD_BORDER);
            prioCell.setBorderWidth(0.5f);
            prioCell.setPadding(8);
            table.addCell(prioCell);

            // Status with color
            String status = task.getStatus() != null ? task.getStatus().name() : "TODO";
            Color statusColor = getStatusColor(status);
            PdfPCell statusCell = new PdfPCell(new Phrase(status.replace("_", " "), FontFactory.getFont(FontFactory.HELVETICA, 9, statusColor)));
            statusCell.setBackgroundColor(rowBg);
            statusCell.setBorderColor(CARD_BORDER);
            statusCell.setBorderWidth(0.5f);
            statusCell.setPadding(8);
            table.addCell(statusCell);

            String deadlineStr = task.getDeadline() != null ? dtf.format(task.getDeadline()) : "—";
            addTableCell(table, deadlineStr, fontTableBody(), rowBg);

            alt = !alt;
        }

        doc.add(table);
    }

    // ── HELPERS ─────────────────────────────────────────────────
    private void addTableCell(PdfPTable table, String text, Font font, Color bg) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(bg);
        cell.setBorderColor(CARD_BORDER);
        cell.setBorderWidth(0.5f);
        cell.setPadding(8);
        table.addCell(cell);
    }

    private void addGradientBar(Document doc) throws DocumentException {
        PdfPTable bar = new PdfPTable(3);
        bar.setWidthPercentage(100);
        bar.setWidths(new float[]{1, 1, 1});

        Color[] gradient = {BRAND_VIOLET, BRAND_CYAN, ACCENT_GREEN};
        for (Color c : gradient) {
            PdfPCell cell = new PdfPCell();
            cell.setBackgroundColor(c);
            cell.setBorder(Rectangle.NO_BORDER);
            cell.setFixedHeight(3);
            bar.addCell(cell);
        }

        doc.add(bar);
    }

    private void addSeparator(Document doc) throws DocumentException {
        PdfPTable sep = new PdfPTable(1);
        sep.setWidthPercentage(100);
        PdfPCell cell = new PdfPCell();
        cell.setBackgroundColor(CARD_BORDER);
        cell.setBorder(Rectangle.NO_BORDER);
        cell.setFixedHeight(1);
        sep.addCell(cell);
        doc.add(sep);
    }

    private Paragraph spacer(int height) {
        Paragraph p = new Paragraph(" ");
        p.setSpacingAfter(height);
        return p;
    }

    private Color getPriorityColor(String priority) {
        return switch (priority) {
            case "URGENT" -> ACCENT_RED;
            case "HIGH"   -> new Color(249, 115, 22);
            case "MEDIUM" -> ACCENT_AMBER;
            case "LOW"    -> ACCENT_GREEN;
            default       -> TEXT_SECONDARY;
        };
    }

    private Color getStatusColor(String status) {
        return switch (status) {
            case "COMPLETED"   -> ACCENT_GREEN;
            case "IN_PROGRESS" -> BRAND_CYAN;
            case "TODO"        -> TEXT_SECONDARY;
            default            -> TEXT_MUTED;
        };
    }

    // ── Dark Page Background Event ──────────────────────────────
    static class DarkPageEvent extends PdfPageEventHelper {
        @Override
        public void onStartPage(PdfWriter writer, Document document) {
            PdfContentByte canvas = writer.getDirectContentUnder();
            canvas.setColorFill(BRAND_DARK);
            canvas.rectangle(0, 0, document.getPageSize().getWidth(), document.getPageSize().getHeight());
            canvas.fill();
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte canvas = writer.getDirectContent();

            // Page number
            Font pageFont = FontFactory.getFont(FontFactory.HELVETICA, 8, TEXT_MUTED);
            Phrase phrase = new Phrase(String.valueOf(writer.getPageNumber()), pageFont);
            ColumnText.showTextAligned(canvas, Element.ALIGN_CENTER, phrase,
                document.getPageSize().getWidth() / 2, 20, 0);

            // Bottom branding line
            Phrase brand = new Phrase("FocusFlow · Productivity Report", FontFactory.getFont(FontFactory.HELVETICA, 7, new Color(50, 50, 60)));
            ColumnText.showTextAligned(canvas, Element.ALIGN_RIGHT, brand,
                document.getPageSize().getWidth() - 36, 20, 0);
        }
    }
}
